### ISSUE TITLE
Peer Review (Alex Shipon)

### ISSUE THREAD

**Issue by ashipon1** [kunjbabson/Webtech-Project#2]
Hi Kunj, great work on your website so far!

After taking a look at your website this is what I recommend:

TECHNICAL ISSUES
-I noticed that you do not seem to have a footer implemented, adding this might be a great tool to help with site organization and overall site flow.
-Another thing worth considering is maybe mixing up the format of your content pages: could add some additional intrigue to your site.

SUGGESTIONS ON CONTENT
-For your "contact us" page, consider adding a drop-down select option for the question "Any specific country or sub-region interested in?". This could be a good way to ensure individuals are contacting about an appropriate location that is covered by your site.
-Also, consider adding images (on your index page) that link to specific tabs that discuss the specified regions/countries. Adding multiple ways to navigate the site is definitely beneficial.

Hope this helps!

Best,
Alex

**Comment by kunjbabson** [comment]
Hi Alex,

Thank you for the valuable inputs! These are extremely helpful and I will try to implement the same.

Best,
Kunj
