### ISSUE TITLE
Peer Review Roberto Canellas

### ISSUE THREAD

**Issue by Rcanellasramirez1** [kunjbabson/Webtech-Project#3]
Hello Kunj love to see that we went after a very similar concept for our websites. 

**Technical Suggestion:**

- Adding a footer would make the page more interactive for the user as they can also navigate the page from the nav-bar and the footer, making it easier for them to reach parts of the website.
- A suggestion for the nav bar would be to make it change colors when the user hover overs making it more interactive and unique.

**Content suggestions:**

- A very cool idea would be to include a video in the home page where we can see an overview of South Asia, this would allow you to hook the viewer from the start with the beauties the region has to offer.
- A great idea that would add more content and depth would be to include industry leader names per region, this would allow for people looking to move to that region to see large employers. 

Hopefully this helps, I look forward to seeing your final version!

Best, 

Roberto

**Comment by kunjbabson** [comment]
Hi Roberto,

Thank you for your valuable inputs! I do agree with them and will try my best to implement them in the final version.

Best,
Kunj
